# Generated by Django 5.1.6 on 2025-02-18 13:48

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShortenedURL",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_url", models.URLField()),
                (
                    "short_code",
                    models.CharField(
                        db_index=True,
                        max_length=6,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(6),
                            django.core.validators.RegexValidator(
                                code="invalid_short_code",
                                message="Short code must contain only letters and numbers.",
                                regex="^[a-zA-Z0-9]+$",
                            ),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
